ssdfskfsjjk
E24035097
]0;E24035097@2015cpp: ~E24035097@2015cpp:~$ pwd
/home/E24035097
]0;E24035097@2015cpp: ~E24035097@2015cpp:~$ go[Kit congi==fig=[K[K[K[K[K[K[K[Kfig -i[KL[KI
error: unknown switch `I'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

]0;E24035097@2015cpp: ~E24035097@2015cpp:~$ [K]0;E24035097@2015cpp: ~E24035097@2015cpp:~$ git config -Ipwd[Kgit config -I[K[K]0;E24035097@2015cpp: ~E24035097@2015cpp:~$ git clone https://github.com/wendy123456/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;E24035097@2015cpp: ~E24035097@2015cpp:~$ exit

Script done on 2016年03月13日 (週日) 14時15分38秒
